'use strict';

module.exports = {
    minions: [
        {
            "name": "Pickford",
            "country": "ENG",
            "club": "Everton",
            "position": "GK",
            "cost": 10,
            "attack": 5,
            "defense": 16,
            "special_trait": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/22/4c/e2/0c/224ce20c.png"
        },
        {
            "name": "Walker",
            "country": "ENG",
            "club": "Man City",
            "position": "DEF",
            "cost": 10,
            "attack": 8,
            "defense": 14,
            "special_trait": "Speed",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b2/c6/3a/4d/b2c63a4d.png"
        },
        {
            "name": "Stones",
            "country": "ENG",
            "club": "Man City",
            "position": "DEF",
            "cost": 10,
            "attack": 6,
            "defense": 14,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c1/29/55/94/c1295594.png"
        },
        {
            "name": "Maguire",
            "country": "ENG",
            "club": "Leicester",
            "position": "DEF",
            "cost": 9,
            "attack": 9,
            "defense": 12,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f1/5f/60/d5/f15f60d5.png"
        },
        {
            "name": "Trippier",
            "country": "ENG",
            "club": "Tottenham",
            "position": "MID",
            "cost": 9,
            "attack": 10,
            "defense": 11,
            "special_trait": "Free kick",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e0/06/10/8f/e006108f.png"
        },
        {
            "name": "Henderson",
            "country": "ENG",
            "club": "Liverpool",
            "position": "MID",
            "cost": 8,
            "attack": 8,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/70/af/3d/83/70af3d83.png"
        },
        {
            "name": "Alli",
            "country": "ENG",
            "club": "Tottenham",
            "position": "MID",
            "cost": 10,
            "attack": 12,
            "defense": 11,
            "special_trait": "Playmaker",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/5a/fa/3c/6b/5afa3c6b.png"
        },
        {
            "name": "Lingard",
            "country": "ENG",
            "club": "Man Utd",
            "position": "MID",
            "cost": 8,
            "attack": 11,
            "defense": 9,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f6/50/90/00/f6509000.png"
        },
        {
            "name": "Young",
            "country": "ENG",
            "club": "Man Utd",
            "position": "MID",
            "cost": 9,
            "attack": 10,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/52/e1/5b/14/52e15b14.png"
        },
        {
            "name": "Sterling",
            "country": "ENG",
            "club": "Man City",
            "position": "ATT",
            "cost": 10,
            "attack": 16,
            "defense": 5,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/82/97/85/39/82978539.png"
        },
        {
            "name": "Kane",
            "country": "ENG",
            "club": "Tottenham",
            "position": "ATT",
            "cost": 15,
            "attack": 25,
            "defense": 10,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/df/53/57/61/df535761.png"
        },
        {
            "name": "Armani",
            "country": "ARG",
            "club": "River Plate",
            "position": "GK",
            "cost": 7,
            "attack": 3,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e4/b5/a4/d7/e4b5a4d7.png"
        },
        {
            "name": "Mercado",
            "country": "ARG",
            "club": "Sevilla",
            "position": "DEF",
            "cost": 7,
            "attack": 4,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b5/03/bc/a6/b503bca6.png"
        },
        {
            "name": "Rojo",
            "country": "ARG",
            "club": "Man Utd",
            "position": "DEF",
            "cost": 8,
            "attack": 8,
            "defense": 9,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a1/31/60/be/a13160be.png"
        },
        {
            "name": "Otamendi",
            "country": "ARG",
            "club": "Man City",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0c/9f/66/35/0c9f6635.png"
        },
        {
            "name": "Tagliafico",
            "country": "ARG",
            "club": "Ajax",
            "position": "DEF",
            "cost": 7,
            "attack": 7,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b6/9a/a3/65/b69aa365.png"
        },
        {
            "name": "Mascherano",
            "country": "ARG",
            "club": "Hebei",
            "position": "MID",
            "cost": 7,
            "attack": 4,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ae/28/74/17/ae287417.png"
        },
        {
            "name": "Biglia",
            "country": "ARG",
            "club": "Milan",
            "position": "MID",
            "cost": 7,
            "attack": 6,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/eb/ae/98/cc/ebae98cc.png"
        },
        {
            "name": "Banega",
            "country": "ARG",
            "club": "Sevilla",
            "position": "MID",
            "cost": 7,
            "attack": 7,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4f/c9/cc/c6/4fc9ccc6.png"
        },
        {
            "name": "Di Maria",
            "country": "ARG",
            "club": "PSG",
            "position": "ATT",
            "cost": 8,
            "attack": 10,
            "defense": 6,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/10/94/a3/8c/1094a38c.png"
        },
        {
            "name": "Messi",
            "country": "ARG",
            "club": "Barcelona",
            "position": "ATT",
            "cost": 15,
            "attack": 25,
            "defense": 7,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/86/8f/60/2f/868f602f.png"
        },
        {
            "name": "Aguero",
            "country": "ARG",
            "club": "Man City",
            "position": "ATT",
            "cost": 10,
            "attack": 16,
            "defense": 5,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4c/ca/ac/4d/4ccaac4d.png"
        },
        {
            "name": "Courtois",
            "country": "BEL",
            "club": "Real Madrid",
            "position": "GK",
            "cost": 12,
            "attack": 6,
            "defense": 18,
            "special_trait": "Diving",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/35/fc/fc/23/35fcfc23.png"
        },
        {
            "name": "Alderweireld",
            "country": "BEL",
            "club": "Tottenham",
            "position": "DEF",
            "cost": 11,
            "attack": 7,
            "defense": 16,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/eb/10/09/28/eb100928.png"
        },
        {
            "name": "Kompany",
            "country": "BEL",
            "club": "Man City",
            "position": "DEF",
            "cost": 11,
            "attack": 8,
            "defense": 15,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0e/5b/98/0d/0e5b980d.png"
        },
        {
            "name": "Vertonghen",
            "country": "BEL",
            "club": "Tottenham",
            "position": "DEF",
            "cost": 11,
            "attack": 8,
            "defense": 16,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f1/46/92/2a/f146922a.png"
        },
        {
            "name": "Meunier",
            "country": "BEL",
            "club": "PSG",
            "position": "MID",
            "cost": 10,
            "attack": 10,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f9/ac/a5/a5/f9aca5a5.png"
        },
        {
            "name": "Witsel",
            "country": "BEL",
            "club": "Dortmund",
            "position": "MID",
            "cost": 11,
            "attack": 12,
            "defense": 11,
            "special_trait": "Ball control",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/18/cb/90/bf/18cb90bf.png"
        },
        {
            "name": "Fellaini",
            "country": "BEL",
            "club": "Man Utd",
            "position": "MID",
            "cost": 10,
            "attack": 9,
            "defense": 12,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/74/9c/80/09/749c8009.png"
        },
        {
            "name": "Chadli",
            "country": "BEL",
            "club": "Monaco",
            "position": "MID",
            "cost": 9,
            "attack": 10,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/47/23/d3/76/4723d376.png"
        },
        {
            "name": "De Bruyne",
            "country": "BEL",
            "club": "Man City",
            "position": "ATT",
            "cost": 12,
            "attack": 15,
            "defense": 11,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b6/31/48/c7/b63148c7.png"
        },
        {
            "name": "Hazard",
            "country": "BEL",
            "club": "Chelsea",
            "position": "ATT",
            "cost": 13,
            "attack": 19,
            "defense": 10,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/32/96/e4/e8/3296e4e8.png"
        },
        {
            "name": "Lukaku",
            "country": "BEL",
            "club": "Man Utd",
            "position": "ATT",
            "cost": 12,
            "attack": 20,
            "defense": 6,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/5c/30/eb/c0/5c30ebc0.png"
        },
        {
            "name": "Alisson",
            "country": "BRA",
            "club": "Liverpool",
            "position": "GK",
            "cost": 11,
            "attack": 6,
            "defense": 17,
            "special_trait": "Diving",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/8b/81/e1/11/8b81e111.png"
        },
        {
            "name": "Fagner",
            "country": "BRA",
            "club": "Corinthians",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f0/22/63/81/f0226381.png"
        },
        {
            "name": "Miranda",
            "country": "BRA",
            "club": "Inter",
            "position": "DEF",
            "cost": 9,
            "attack": 6,
            "defense": 12,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ec/05/0a/15/ec050a15.png"
        },
        {
            "name": "Thiago Silva",
            "country": "BRA",
            "club": "PSG",
            "position": "DEF",
            "cost": 10,
            "attack": 6,
            "defense": 13,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/33/76/cd/67/3376cd67.png"
        },
        {
            "name": "Marcelo",
            "country": "BRA",
            "club": "Real Madrid",
            "position": "DEF",
            "cost": 10,
            "attack": 10,
            "defense": 11,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f5/f2/86/78/f5f28678.png"
        },
        {
            "name": "Fernandinho",
            "country": "BRA",
            "club": "Man City",
            "position": "MID",
            "cost": 9,
            "attack": 6,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/15/e6/c6/7f/15e6c67f.png"
        },
        {
            "name": "Paulinho",
            "country": "BRA",
            "club": "Guangzhou",
            "position": "MID",
            "cost": 9,
            "attack": 8,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/7c/b9/84/23/7cb98423.png"
        },
        {
            "name": "Coutinho",
            "country": "BRA",
            "club": "Barcelona",
            "position": "MID",
            "cost": 11,
            "attack": 15,
            "defense": 8,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/82/cd/d3/de/82cdd3de.png"
        },
        {
            "name": "Willian",
            "country": "BRA",
            "club": "Chelsea",
            "position": "ATT",
            "cost": 10,
            "attack": 14,
            "defense": 6,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4e/68/4e/82/4e684e82.png"
        },
        {
            "name": "Neymar",
            "country": "BRA",
            "club": "PSG",
            "position": "ATT",
            "cost": 12,
            "attack": 18,
            "defense": 6,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/5a/bc/0f/42/5abc0f42.png"
        },
        {
            "name": "Gabriel Jesus",
            "country": "BRA",
            "club": "Man City",
            "position": "ATT",
            "cost": 9,
            "attack": 12,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/65/38/f9/ee/6538f9ee.png"
        },
        {
            "name": "Ospina",
            "country": "COL",
            "club": "Napoli",
            "position": "GK",
            "cost": 8,
            "attack": 6,
            "defense": 12,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/dd/ac/a1/78/ddaca178.png"
        },
        {
            "name": "Arias",
            "country": "COL",
            "club": "Atletico",
            "position": "DEF",
            "cost": 9,
            "attack": 8,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/45/12/21/1a/4512211a.png"
        },
        {
            "name": "D.Sanchez",
            "country": "COL",
            "club": "Tottenham",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/cc/3c/02/72/cc3c0272.png"
        },
        {
            "name": "Mina",
            "country": "COL",
            "club": "Everton",
            "position": "DEF",
            "cost": 11,
            "attack": 10,
            "defense": 13,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/fc/de/62/ed/fcde62ed.png"
        },
        {
            "name": "Mojica",
            "country": "COL",
            "club": "Girona",
            "position": "DEF",
            "cost": 7,
            "attack": 6,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c6/cd/a9/19/c6cda919.png"
        },
        {
            "name": "C.Sanchez",
            "country": "COL",
            "club": "West Ham",
            "position": "MID",
            "cost": 8,
            "attack": 6,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/bf/8c/7a/a8/bf8c7aa8.png"
        },
        {
            "name": "Barrios",
            "country": "COL",
            "club": "Boca Juniors",
            "position": "MID",
            "cost": 8,
            "attack": 5,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/80/e8/fd/74/80e8fd74.png"
        },
        {
            "name": "Quintero",
            "country": "COL",
            "club": "River Plate",
            "position": "MID",
            "cost": 9,
            "attack": 13,
            "defense": 6,
            "special_trait": "Playmaker",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/09/a2/0c/68/09a20c68.png"
        },
        {
            "name": "Cuadrado",
            "country": "COL",
            "club": "Juventus",
            "position": "ATT",
            "cost": 10,
            "attack": 12,
            "defense": 8,
            "special_trait": "Speed",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e8/5c/1c/0a/e85c1c0a.png"
        },
        {
            "name": "James",
            "country": "COL",
            "club": "Bayern",
            "position": "ATT",
            "cost": 11,
            "attack": 15,
            "defense": 8,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b0/76/99/2b/b076992b.png"
        },
        {
            "name": "Falcao",
            "country": "COL",
            "club": "Monaco",
            "position": "ATT",
            "cost": 11,
            "attack": 15,
            "defense": 7,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/99/ac/10/15/99ac1015.png"
        },
        {
            "name": "Subasic",
            "country": "CRO",
            "club": "Monaco",
            "position": "GK",
            "cost": 11,
            "attack": 6,
            "defense": 17,
            "special_trait": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e3/47/77/d7/e34777d7.png"
        },
        {
            "name": "Vrsaljko",
            "country": "CRO",
            "club": "Inter",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 13,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/00/f4/95/0a/00f4950a.png"
        },
        {
            "name": "Lovren",
            "country": "CRO",
            "club": "Liverpool",
            "position": "DEF",
            "cost": 11,
            "attack": 7,
            "defense": 16,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/53/74/d7/d7/5374d7d7.png"
        },
        {
            "name": "Vida",
            "country": "CRO",
            "club": "Besiktas",
            "position": "DEF",
            "cost": 10,
            "attack": 8,
            "defense": 13,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/eb/b5/3f/8f/ebb53f8f.png"
        },
        {
            "name": "Strinic",
            "country": "CRO",
            "club": "Milan",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/22/dc/69/24/22dc6924.png"
        },
        {
            "name": "Brozovic",
            "country": "CRO",
            "club": "Inter",
            "position": "MID",
            "cost": 9,
            "attack": 9,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0b/09/94/6d/0b09946d.png"
        },
        {
            "name": "Rakitic",
            "country": "CRO",
            "club": "Barcelona",
            "position": "MID",
            "cost": 11,
            "attack": 12,
            "defense": 11,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a4/e2/f5/1e/a4e2f51e.png"
        },
        {
            "name": "Modric",
            "country": "CRO",
            "club": "Real Madrid",
            "position": "MID",
            "cost": 14,
            "attack": 16,
            "defense": 16,
            "special_trait": "Playmaker",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f4/82/1b/c6/f4821bc6.png"
        },
        {
            "name": "Rebic",
            "country": "CRO",
            "club": "Frankfurt",
            "position": "ATT",
            "cost": 10,
            "attack": 15,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/79/55/9c/54/79559c54.png"
        },
        {
            "name": "Perisic",
            "country": "CRO",
            "club": "Inter",
            "position": "ATT",
            "cost": 12,
            "attack": 17,
            "defense": 8,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ef/4d/4f/63/ef4d4f63.png"
        },
        {
            "name": "Mandzukic",
            "country": "CRO",
            "club": "Juventus",
            "position": "ATT",
            "cost": 12,
            "attack": 18,
            "defense": 8,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/fc/83/27/5b/fc83275b.png"
        },
        {
            "name": "Schmeichel",
            "country": "DEN",
            "club": "Leicester",
            "position": "GK",
            "cost": 11,
            "attack": 6,
            "defense": 17,
            "special_trait": "Diving",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c5/6a/bd/c8/c56abdc8.png"
        },
        {
            "name": "Dalsgaard",
            "country": "DEN",
            "club": "Brentford",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/00/24/9b/5e/00249b5e.png"
        },
        {
            "name": "Zanka",
            "country": "DEN",
            "club": "Huddersfield",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/7b/e0/a9/73/7be0a973.png"
        },
        {
            "name": "Kjaer",
            "country": "DEN",
            "club": "Sevilla",
            "position": "DEF",
            "cost": 9,
            "attack": 7,
            "defense": 11,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0e/dc/67/d1/0edc67d1.png"
        },
        {
            "name": "Larsen",
            "country": "DEN",
            "club": "Udinese",
            "position": "DEF",
            "cost": 6,
            "attack": 5,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0f/bb/d7/98/0fbbd798.png"
        },
        {
            "name": "Christensen",
            "country": "DEN",
            "club": "Chelsea",
            "position": "MID",
            "cost": 9,
            "attack": 6,
            "defense": 12,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ce/ed/ee/d6/ceedeed6.png"
        },
        {
            "name": "Delaney",
            "country": "DEN",
            "club": "Dortmund",
            "position": "MID",
            "cost": 9,
            "attack": 9,
            "defense": 10,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/32/1d/9f/aa/321d9faa.png"
        },
        {
            "name": "Eriksen",
            "country": "DEN",
            "club": "Tottenham",
            "position": "MID",
            "cost": 11,
            "attack": 15,
            "defense": 9,
            "special_trait": "Ball control",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/81/bf/59/0d/81bf590d.png"
        },
        {
            "name": "Braithwaite",
            "country": "DEN",
            "club": "Middlesbrough",
            "position": "ATT",
            "cost": 7,
            "attack": 9,
            "defense": 4,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f9/5e/fa/20/f95efa20.png"
        },
        {
            "name": "Sisto",
            "country": "DEN",
            "club": "Celta Vigo",
            "position": "ATT",
            "cost": 8,
            "attack": 12,
            "defense": 5,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/78/12/3b/8c/78123b8c.png"
        },
        {
            "name": "Poulsen",
            "country": "DEN",
            "club": "Leipzig",
            "position": "ATT",
            "cost": 9,
            "attack": 13,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/7d/fc/1f/6a/7dfc1f6a.png"
        },
        {
            "name": "Sommer",
            "country": "SUI",
            "club": "Gladbach",
            "position": "GK",
            "cost": 9,
            "attack": 5,
            "defense": 13,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/78/40/6c/a0/78406ca0.png"
        },
        {
            "name": "Lang",
            "country": "SUI",
            "club": "Gladbach",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b9/13/b7/42/b913b742.png"
        },
        {
            "name": "Akanji",
            "country": "SUI",
            "club": "Dortmund",
            "position": "DEF",
            "cost": 10,
            "attack": 8,
            "defense": 13,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e8/43/77/82/e8437782.png"
        },
        {
            "name": "Droujou",
            "country": "SUI",
            "club": "SPAL",
            "position": "DEF",
            "cost": 7,
            "attack": 6,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/30/27/fc/54/3027fc54.png"
        },
        {
            "name": "Rodriguez",
            "country": "SUI",
            "club": "Milan",
            "position": "DEF",
            "cost": 9,
            "attack": 7,
            "defense": 11,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/25/ed/9f/a3/25ed9fa3.png"
        },
        {
            "name": "Xhaka",
            "country": "SUI",
            "club": "Arsenal",
            "position": "MID",
            "cost": 10,
            "attack": 12,
            "defense": 8,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/eb/36/14/68/eb361468.png"
        },
        {
            "name": "Behrami",
            "country": "SUI",
            "club": "Udinese",
            "position": "MID",
            "cost": 7,
            "attack": 7,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f5/75/d5/3e/f575d53e.png"
        },
        {
            "name": "Dzemaili",
            "country": "SUI",
            "club": "Bologna",
            "position": "MID",
            "cost": 7,
            "attack": 7,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/9b/91/fd/2c/9b91fd2c.png"
        },
        {
            "name": "Shaqiri",
            "country": "SUI",
            "club": "Liverpool",
            "position": "ATT",
            "cost": 10,
            "attack": 14,
            "defense": 7,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f8/1f/34/d5/f81f34d5.png"
        },
        {
            "name": "Zuber",
            "country": "SUI",
            "club": "Hoffenheim",
            "position": "ATT",
            "cost": 9,
            "attack": 12,
            "defense": 7,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/76/8b/2e/fa/768b2efa.png"
        },
        {
            "name": "Seferovic",
            "country": "SUI",
            "club": "Benfica",
            "position": "ATT",
            "cost": 8,
            "attack": 11,
            "defense": 5,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/2d/a7/46/65/2da74665.png"
        },
        {
            "name": "Lloris",
            "country": "FRA",
            "club": "Tottenham",
            "position": "GK",
            "cost": 11,
            "attack": 6,
            "defense": 17,
            "special_trait": "Diving",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/29/19/07/54/29190754.png"
        },
        {
            "name": "Pavard",
            "country": "FRA",
            "club": "Stuttgart",
            "position": "DEF",
            "cost": 11,
            "attack": 9,
            "defense": 15,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/06/59/3a/4a/06593a4a.png"
        },
        {
            "name": "Umtiti",
            "country": "FRA",
            "club": "Barcelona",
            "position": "DEF",
            "cost": 10,
            "attack": 8,
            "defense": 13,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/5c/d0/d0/67/5cd0d067.png"
        },
        {
            "name": "Varane",
            "country": "FRA",
            "club": "Real Madrid",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 14,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f2/ac/b7/90/f2acb790.png"
        },
        {
            "name": "Hernandez",
            "country": "FRA",
            "club": "Atletico",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 14,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/8e/f3/fc/38/8ef3fc38.png"
        },
        {
            "name": "Kante",
            "country": "FRA",
            "club": "Chelsea",
            "position": "MID",
            "cost": 11,
            "attack": 8,
            "defense": 16,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/71/95/bf/bc/7195bfbc.png"
        },
        {
            "name": "Pogba",
            "country": "FRA",
            "club": "Man Utd",
            "position": "MID",
            "cost": 11,
            "attack": 12,
            "defense": 11,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a6/67/4b/05/a6674b05.png"
        },
        {
            "name": "Matuidi",
            "country": "FRA",
            "club": "Juventus",
            "position": "MID",
            "cost": 10,
            "attack": 8,
            "defense": 12,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ae/a7/9b/2e/aea79b2e.png"
        },
        {
            "name": "Mbappe",
            "country": "FRA",
            "club": "PSG",
            "position": "ATT",
            "cost": 13,
            "attack": 21,
            "defense": 9,
            "special_trait": "Speed",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/d4/b3/4f/d1/d4b34fd1.png"
        },
        {
            "name": "Griezmann",
            "country": "FRA",
            "club": "Atletico",
            "position": "ATT",
            "cost": 13,
            "attack": 19,
            "defense": 10,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/25/e0/35/5a/25e0355a.png"
        },
        {
            "name": "Giroud",
            "country": "FRA",
            "club": "Chelsea",
            "position": "ATT",
            "cost": 9,
            "attack": 12,
            "defense": 6,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/97/2c/9b/e4/972c9be4.png"
        },
        {
            "name": "Kawashima",
            "country": "JPA",
            "club": "Strasbourg",
            "position": "GK",
            "cost": 7,
            "attack": 5,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/1b/34/8e/fb/1b348efb.png"
        },
        {
            "name": "Sakai",
            "country": "JPA",
            "club": "Marseille",
            "position": "DEF",
            "cost": 7,
            "attack": 6,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/dc/47/82/5c/dc47825c.png"
        },
        {
            "name": "Shoji",
            "country": "JPA",
            "club": "Kashima",
            "position": "DEF",
            "cost": 7,
            "attack": 4,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/3f/54/bc/07/3f54bc07.png"
        },
        {
            "name": "Yoshida",
            "country": "JPA",
            "club": "Southampton",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f6/f1/47/03/f6f14703.png"
        },
        {
            "name": "Nagatomo",
            "country": "JPA",
            "club": "Galatasaray",
            "position": "DEF",
            "cost": 7,
            "attack": 6,
            "defense": 8,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/91/0a/16/89/910a1689.png"
        },
        {
            "name": "Hasebe",
            "country": "JPA",
            "club": "Frankfurt",
            "position": "MID",
            "cost": 7,
            "attack": 6,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/cf/8a/8a/b0/cf8a8ab0.png"
        },
        {
            "name": "Shibasaki",
            "country": "JPA",
            "club": "Getafe",
            "position": "MID",
            "cost": 7,
            "attack": 6,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f3/e2/14/05/f3e21405.png"
        },
        {
            "name": "Kagawa",
            "country": "JPA",
            "club": "Dortmund",
            "position": "MID",
            "cost": 8,
            "attack": 10,
            "defense": 7,
            "special_trait": "Playmaker",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/3e/26/26/da/3e2626da.png"
        },
        {
            "name": "Haraguchi",
            "country": "JPA",
            "club": "Hannover",
            "position": "ATT",
            "cost": 8,
            "attack": 10,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/36/cc/63/34/36cc6334.png"
        },
        {
            "name": "Inui",
            "country": "JPA",
            "club": "Betis",
            "position": "ATT",
            "cost": 8,
            "attack": 11,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/85/23/86/97/85238697.png"
        },
        {
            "name": "Osako",
            "country": "JPA",
            "club": "Bremen",
            "position": "ATT",
            "cost": 8,
            "attack": 12,
            "defense": 5,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/9a/48/6a/6d/9a486a6d.png"
        },
        {
            "name": "Ochoa",
            "country": "MEX",
            "club": "Standard",
            "position": "GK",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": "Diving",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a2/c5/bc/68/a2c5bc68.png"
        },
        {
            "name": "Layun",
            "country": "MEX",
            "club": "Villarreal",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/34/f4/0b/81/34f40b81.png"
        },
        {
            "name": "Salcedo",
            "country": "MEX",
            "club": "Frankfurt",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/10/83/f6/26/1083f626.png"
        },
        {
            "name": "Ayala",
            "country": "MEX",
            "club": "UNAL",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/cf/e2/98/09/cfe29809.png"
        },
        {
            "name": "Gallardo",
            "country": "MEX",
            "club": "Monterrey",
            "position": "DEF",
            "cost": 7,
            "attack": 6,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/8f/57/56/9e/8f57569e.png"
        },
        {
            "name": "Marquez",
            "country": "MEX",
            "club": "Atlas",
            "position": "MID",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/d5/76/de/47/d576de47.png"
        },
        {
            "name": "Guardado",
            "country": "MEX",
            "club": "Betis",
            "position": "MID",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f8/22/af/41/f822af41.png"
        },
        {
            "name": "Herrera",
            "country": "MEX",
            "club": "Porto",
            "position": "MID",
            "cost": 8,
            "attack": 8,
            "defense": 9,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/58/45/6e/ec/58456eec.png"
        },
        {
            "name": "Vela",
            "country": "MEX",
            "club": "Los Angeles",
            "position": "ATT",
            "cost": 8,
            "attack": 12,
            "defense": 5,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/fa/b0/d0/cc/fab0d0cc.png"
        },
        {
            "name": "Lozano",
            "country": "MEX",
            "club": "PSV",
            "position": "ATT",
            "cost": 9,
            "attack": 14,
            "defense": 5,
            "special_trait": "Speed",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/42/28/18/be/422818be.png"
        },
        {
            "name": "Chicharito",
            "country": "MEX",
            "club": "West Ham",
            "position": "ATT",
            "cost": 8,
            "attack": 10,
            "defense": 5,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/fc/7e/42/8f/fc7e428f.png"
        },
        {
            "name": "Rui Patricio",
            "country": "POR",
            "club": "Wolves",
            "position": "GK",
            "cost": 8,
            "attack": 5,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/16/78/ec/0d/1678ec0d.png"
        },
        {
            "name": "Cedric",
            "country": "POR",
            "club": "Southampton",
            "position": "DEF",
            "cost": 7,
            "attack": 5,
            "defense": 9,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/62/9f/14/04/629f1404.png"
        },
        {
            "name": "Pepe",
            "country": "POR",
            "club": "Besiktas",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 14,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/1c/3e/74/25/1c3e7425.png"
        },
        {
            "name": "Fonte",
            "country": "POR",
            "club": "Lille",
            "position": "DEF",
            "cost": 8,
            "attack": 5,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c2/43/15/8e/c243158e.png"
        },
        {
            "name": "Guerreiro",
            "country": "POR",
            "club": "Dortmund",
            "position": "DEF",
            "cost": 8,
            "attack": 7,
            "defense": 10,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/dd/f0/a2/2a/ddf0a22a.png"
        },
        {
            "name": "W.Carvalho",
            "country": "POR",
            "club": "Betis",
            "position": "MID",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/85/75/8c/0d/85758c0d.png"
        },
        {
            "name": "Moutinho",
            "country": "POR",
            "club": "Wolves",
            "position": "MID",
            "cost": 7,
            "attack": 6,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/83/ea/23/3a/83ea233a.png"
        },
        {
            "name": "B.Silva",
            "country": "POR",
            "club": "Man City",
            "position": "MID",
            "cost": 9,
            "attack": 12,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/86/d2/eb/40/86d2eb40.png"
        },
        {
            "name": "Guedes",
            "country": "POR",
            "club": "Valencia",
            "position": "MID",
            "cost": 8,
            "attack": 9,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/bf/43/e4/73/bf43e473.png"
        },
        {
            "name": "C.Ronaldo",
            "country": "POR",
            "club": "Juventus",
            "position": "ATT",
            "cost": 15,
            "attack": 25,
            "defense": 8,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b1/36/ce/cf/b136cecf.png"
        },
        {
            "name": "A.Silva",
            "country": "POR",
            "club": "Sevilla",
            "position": "ATT",
            "cost": 7,
            "attack": 10,
            "defense": 3,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/bc/83/69/76/bc836976.png"
        },
        {
            "name": "Akinfeev",
            "country": "RUS",
            "club": "CSKA",
            "position": "GK",
            "cost": 10,
            "attack": 6,
            "defense": 16,
            "special_trait": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/09/7d/2f/dd/097d2fdd.png"
        },
        {
            "name": "M.Fernandes",
            "country": "RUS",
            "club": "CSKA",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 14,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4e/dd/5c/01/4edd5c01.png"
        },
        {
            "name": "Ignashevich",
            "country": "RUS",
            "club": "CSKA",
            "position": "DEF",
            "cost": 9,
            "attack": 6,
            "defense": 13,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/41/68/2d/63/41682d63.png"
        },
        {
            "name": "Kutepov",
            "country": "RUS",
            "club": "Spartak",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4f/ef/9d/e7/4fef9de7.png"
        },
        {
            "name": "Zhirkov",
            "country": "RUS",
            "club": "Zenit",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/73/a8/be/6e/73a8be6e.png"
        },
        {
            "name": "Gazinsky",
            "country": "RUS",
            "club": "Krasnodar",
            "position": "MID",
            "cost": 9,
            "attack": 8,
            "defense": 11,
            "special_trait": "Ball control",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4a/f2/2b/c4/4af22bc4.png"
        },
        {
            "name": "Zobnin",
            "country": "RUS",
            "club": "Spartak",
            "position": "MID",
            "cost": 9,
            "attack": 7,
            "defense": 12,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/3f/b8/91/44/3fb89144.png"
        },
        {
            "name": "Golovin",
            "country": "RUS",
            "club": "Monaco",
            "position": "MID",
            "cost": 11,
            "attack": 15,
            "defense": 10,
            "special_trait": "Playmaker",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c1/87/34/9a/c187349a.png"
        },
        {
            "name": "Samedov",
            "country": "RUS",
            "club": "Spartak",
            "position": "ATT",
            "cost": 7,
            "attack": 8,
            "defense": 5,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/23/0c/11/f7/230c11f7.png"
        },
        {
            "name": "Cheryshev",
            "country": "RUS",
            "club": "Valencia",
            "position": "ATT",
            "cost": 11,
            "attack": 16,
            "defense": 9,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f7/e9/49/24/f7e94924.png"
        },
        {
            "name": "Dzyuba",
            "country": "RUS",
            "club": "Zenit",
            "position": "ATT",
            "cost": 11,
            "attack": 17,
            "defense": 8,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ba/17/cb/6f/ba17cb6f.png"
        },
        {
            "name": "De Gea",
            "country": "ESP",
            "club": "Man Utd",
            "position": "GK",
            "cost": 10,
            "attack": 6,
            "defense": 13,
            "special_trait": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b6/2b/ee/11/b62bee11.png"
        },
        {
            "name": "Carvajal",
            "country": "ESP",
            "club": "Real Madrid",
            "position": "DEF",
            "cost": 9,
            "attack": 6,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/8f/62/bc/54/8f62bc54.png"
        },
        {
            "name": "Ramos",
            "country": "ESP",
            "club": "Real Madrid",
            "position": "DEF",
            "cost": 10,
            "attack": 7,
            "defense": 13,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a1/bb/97/12/a1bb9712.png"
        },
        {
            "name": "Pique",
            "country": "ESP",
            "club": "Barcelona",
            "position": "DEF",
            "cost": 10,
            "attack": 6,
            "defense": 13,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/86/dc/f5/41/86dcf541.png"
        },
        {
            "name": "J.Alba",
            "country": "ESP",
            "club": "Barcelona",
            "position": "DEF",
            "cost": 9,
            "attack": 7,
            "defense": 11,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/10/ee/2d/3a/10ee2d3a.png"
        },
        {
            "name": "Busquets",
            "country": "ESP",
            "club": "Barcelona",
            "position": "MID",
            "cost": 9,
            "attack": 5,
            "defense": 13,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4b/12/ae/ec/4b12aeec.png"
        },
        {
            "name": "Koke",
            "country": "ESP",
            "club": "Atletico",
            "position": "MID",
            "cost": 8,
            "attack": 7,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ea/4c/0f/27/ea4c0f27.png"
        },
        {
            "name": "D.Silva",
            "country": "ESP",
            "club": "Man City",
            "position": "MID",
            "cost": 10,
            "attack": 12,
            "defense": 8,
            "special_trait": "Passing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c0/c3/e1/e3/c0c3e1e3.png"
        },
        {
            "name": "Isco",
            "country": "ESP",
            "club": "Real Madrid",
            "position": "ATT",
            "cost": 10,
            "attack": 13,
            "defense": 8,
            "special_trait": "Dribbling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/83/d1/58/a6/83d158a6.png"
        },
        {
            "name": "Asensio",
            "country": "ESP",
            "club": "Real Madrid",
            "position": "ATT",
            "cost": 9,
            "attack": 11,
            "defense": 7,
            "special_trait": "Long shot",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/96/83/65/24/96836524.png"
        },
        {
            "name": "D.Costa",
            "country": "ESP",
            "club": "Atletico",
            "position": "ATT",
            "cost": 9,
            "attack": 13,
            "defense": 6,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/d8/5b/2c/23/d85b2c23.png"
        },
        {
            "name": "Olsen",
            "country": "SWE",
            "club": "Roma",
            "position": "GK",
            "cost": 11,
            "attack": 8,
            "defense": 16,
            "special_trait": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/24/2d/e7/a2/242de7a2.png"
        },
        {
            "name": "Lustig",
            "country": "SWE",
            "club": "Celtic",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 13,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0d/ca/d3/01/0dcad301.png"
        },
        {
            "name": "Granqvist",
            "country": "SWE",
            "club": "Helsingborgs",
            "position": "DEF",
            "cost": 11,
            "attack": 8,
            "defense": 16,
            "special_trait": "Strength",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/38/c9/29/3b/38c9293b.png"
        },
        {
            "name": "Lindelhof",
            "country": "SWE",
            "club": "Man Utd",
            "position": "DEF",
            "cost": 9,
            "attack": 6,
            "defense": 12,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c2/0e/8f/95/c20e8f95.png"
        },
        {
            "name": "Augustinsson",
            "country": "SWE",
            "club": "Bremen",
            "position": "DEF",
            "cost": 8,
            "attack": 5,
            "defense": 11,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/bb/42/1c/ba/bb421cba.png"
        },
        {
            "name": "Claesson",
            "country": "SWE",
            "club": "Krasnodar",
            "position": "MID",
            "cost": 8,
            "attack": 11,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/dc/a5/3f/8b/dca53f8b.png"
        },
        {
            "name": "Ekdal",
            "country": "SWE",
            "club": "Sampdoria",
            "position": "MID",
            "cost": 8,
            "attack": 8,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/82/43/1a/3e/82431a3e.png"
        },
        {
            "name": "Larsson",
            "country": "SWE",
            "club": "AIK",
            "position": "MID",
            "cost": 8,
            "attack": 9,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/6a/9f/81/e5/6a9f81e5.png"
        },
        {
            "name": "Forsberg",
            "country": "SWE",
            "club": "Leipzig",
            "position": "MID",
            "cost": 10,
            "attack": 13,
            "defense": 8,
            "special_trait": "Crossing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/7f/6a/07/08/7f6a0708.png"
        },
        {
            "name": "Berg",
            "country": "SWE",
            "club": "Al Ain",
            "position": "ATT",
            "cost": 10,
            "attack": 15,
            "defense": 7,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ea/d3/58/b3/ead358b3.png"
        },
        {
            "name": "Toivonen",
            "country": "SWE",
            "club": "Melbourne",
            "position": "ATT",
            "cost": 10,
            "attack": 14,
            "defense": 7,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/86/8a/1c/e3/868a1ce3.png"
        },
        {
            "name": "Muslera",
            "country": "URU",
            "club": "Galatasaray",
            "position": "GK",
            "cost": 8,
            "attack": 5,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e8/6a/ad/29/e86aad29.png"
        },
        {
            "name": "Caceres",
            "country": "URU",
            "club": "Lazio",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/29/a9/04/24/29a90424.png"
        },
        {
            "name": "Godin",
            "country": "URU",
            "club": "Atletico",
            "position": "DEF",
            "cost": 11,
            "attack": 7,
            "defense": 16,
            "special_trait": "Heading",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/97/93/f0/a5/9793f0a5.png"
        },
        {
            "name": "Gimenez",
            "country": "URU",
            "club": "Atletico",
            "position": "DEF",
            "cost": 10,
            "attack": 6,
            "defense": 14,
            "special_trait": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/24/f3/3a/57/24f33a57.png"
        },
        {
            "name": "Laxalt",
            "country": "URU",
            "club": "Milan",
            "position": "DEF",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/52/e1/f4/ef/52e1f4ef.png"
        },
        {
            "name": "Torreira",
            "country": "URU",
            "club": "Arsenal",
            "position": "MID",
            "cost": 8,
            "attack": 8,
            "defense": 8,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/2b/10/2e/a9/2b102ea9.png"
        },
        {
            "name": "Vecino",
            "country": "URU",
            "club": "Inter",
            "position": "MID",
            "cost": 8,
            "attack": 6,
            "defense": 10,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/b5/6b/4d/43/b56b4d43.png"
        },
        {
            "name": "Nandez",
            "country": "URU",
            "club": "Boca Juniors",
            "position": "MID",
            "cost": 7,
            "attack": 6,
            "defense": 7,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0b/0a/1f/c7/0b0a1fc7.png"
        },
        {
            "name": "Bentancur",
            "country": "URU",
            "club": "Juventus",
            "position": "MID",
            "cost": 7,
            "attack": 8,
            "defense": 6,
            "special_trait": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/1d/20/21/2e/1d20212e.png"
        },
        {
            "name": "Suarez",
            "country": "URU",
            "club": "Barcelona",
            "position": "ATT",
            "cost": 11,
            "attack": 17,
            "defense": 8,
            "special_trait": "Free kick",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c4/e4/ba/fd/c4e4bafd.png"
        },
        {
            "name": "Cavani",
            "country": "URU",
            "club": "PSG",
            "position": "ATT",
            "cost": 11,
            "attack": 17,
            "defense": 8,
            "special_trait": "Finishing",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/21/3b/da/2b/213bda2b.png"
        }
    ],
    functional: [
        {
            "name": "Yellow Card",
            "who_applies_to": "Opposition",
            "attack": null,
            "for_total_attack": "no",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": -5,
            "for_total_defence": "yes",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/bc/5d/18/47/bc5d1847.png" 
        },
        {
            "name": "Red Card",
            "who_applies_to": "Opposition",
            "attack": -10,
            "for_total_attack": "yes",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": -10,
            "for_total_defence": "yes",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/79/51/3d/6a/79513d6a.png" 
        },
        {
            "name": "Corner",
            "who_applies_to": "My team",
            "attack": 5,
            "for_total_attack": "no",
            "attack_special_trait_1": "Crossing",
            "attack_special_trait_2": "Heading",
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/1f/ab/8e/b3/1fab8eb3.png" 
        },
        {
            "name": "Penalty",
            "who_applies_to": "My team",
            "attack": 10,
            "for_total_attack": "no",
            "attack_special_trait_1": "Finishing",
            "attack_special_trait_2": null,
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e2/95/09/e0/e29509e0.png" 
        },
        {
            "name": "Free Kick",
            "who_applies_to": "My team",
            "attack": 7,
            "for_total_attack": "no",
            "attack_special_trait_1": "Long shot",
            "attack_special_trait_2": "Free kick",
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/34/f9/3a/c3/34f93ac3.png" 
        },
        {
            "name": "Counter Attack",
            "who_applies_to": "My team",
            "attack": 7,
            "for_total_attack": "no",
            "attack_special_trait_1": "Dribbling",
            "attack_special_trait_2": "Speed",
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/82/67/55/15/82675515.png" 
        },
        {
            "name": "Tap In",
            "who_applies_to": "My team",
            "attack": 5,
            "for_total_attack": "no",
            "attack_special_trait_1": "Crossing",
            "attack_special_trait_2": "Finishing",
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/17/49/1e/b8/17491eb8.png" 
        },
        {
            "name": "Target Man",
            "who_applies_to": "My team",
            "attack": 5,
            "for_total_attack": "no",
            "attack_special_trait_1": "Heading",
            "attack_special_trait_2": "Ball controll",
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/0d/cf/b8/69/0dcfb869.png" 
        },
        {
            "name": "Park the Bus",
            "who_applies_to": "My team",
            "attack": null,
            "for_total_attack": "no",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": 10,
            "for_total_defence": "yes",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/59/ce/90/07/59ce9007.png" 
        },
        {
            "name": "Ultra Attack",
            "who_applies_to": "My team",
            "attack": 10,
            "for_total_attack": "yes",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e6/e6/a2/74/e6e6a274.png" 
        },
        {
            "name": "Heavy Rain",
            "who_applies_to": "All",
            "attack": 3,
            "for_total_attack": "no",
            "attack_special_trait_1": "Tackling",
            "attack_special_trait_2": "Long shot",
            "defence": -5,
            "for_total_defence": "no",
            "defence_special_trait_1": "Dribbling",
            "defence_special_trait_2": "Ball control",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/5f/7a/b3/73/5f7ab373.png" 
        },
        {
            "name": "Disaster",
            "who_applies_to": "All",
            "attack": "-all",
            "for_total_attack": "yes",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": "-all",
            "for_total_defence": "yes",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f6/8a/5c/bd/f68a5cbd.png" 
        },
        {
            "name": "Melee",
            "who_applies_to": "All",
            "attack": -10,
            "for_total_attack": "yes",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": -10,
            "for_total_defence": "yes",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f7/c6/f1/6f/f7c6f16f.png" 
        },
        {
            "name": "Tiki Taka",
            "who_applies_to": "My team",
            "attack": 8,
            "for_total_attack": "no",
            "attack_special_trait_1": "Passing",
            "attack_special_trait_2": "Ball controll",
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ac/4e/52/1f/ac4e521f.png" 
        },
        {
            "name": "Physical Game",
            "who_applies_to": "All",
            "attack": -3,
            "for_total_attack": "no",
            "attack_special_trait_1": "Dribbling",
            "attack_special_trait_2": "Ball controll",
            "defence": 7,
            "for_total_defence": "no",
            "defence_special_trait_1": "Strength",
            "defence_special_trait_2": "Tackling",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/6b/c3/eb/0e/6bc3eb0e.png" 
        },
        {
            "name": "Show",
            "who_applies_to": "All",
            "attack": 2,
            "for_total_attack": "no",
            "attack_special_trait_1": "not null",
            "attack_special_trait_2": null,
            "defence": 2,
            "for_total_defence": "no",
            "defence_special_trait_1": "not null",
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/31/67/42/9e/3167429e.png" 
        },
        {
            "name": "Joga Bonito",
            "who_applies_to": "All",
            "attack": 10,
            "for_total_attack": "no",
            "attack_special_trait_1": "Dribbling",
            "attack_special_trait_2": null,
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/aa/ab/29/e4/aaab29e4.png" 
        },
        {
            "name": "Fog",
            "who_applies_to": "All",
            "attack": 10,
            "for_total_attack": "no",
            "attack_special_trait_1": "Playmaker",
            "attack_special_trait_2": null,
            "defence": null,
            "for_total_defence": "no",
            "defence_special_trait_1": null,
            "defence_special_trait_2": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/c6/09/e4/e5/c609e4e5.png" 
        },
        {
            "name": "Flying High",
            "who_applies_to": "My team",
            "attack": null,
            "for_total_attack": "no",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": 8,
            "for_total_defence": "no",
            "defence_special_trait_1": "Diving",
            "defence_special_trait_2": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/99/ab/b3/34/99abb334.png" 
        },
        {
            "name": "Slippery",
            "who_applies_to": "Opposition",
            "attack": null,
            "for_total_attack": "no",
            "attack_special_trait_1": null,
            "attack_special_trait_2": null,
            "defence": -5,
            "for_total_defence": "no",
            "defence_special_trait_1": "Diving",
            "defence_special_trait_2": "Reflexes",
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/9b/12/0c/a9/9b120ca9.png" 
        }
    ],
    heroes: [
        {
            "name": "Deschamps",
            "country": "FRA",
            "country_attack": 3,
            "country_defence": 3,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a0/0c/3f/e0/a00c3fe0.png"
        },
        {
            "name": "Lopetegui",
            "country": "ESP",
            "country_attack": -2,
            "country_defence": -2,
            "club": "Real Madrid",
            "club_attack": 2,
            "club_defence": 2,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a9/03/a8/cb/a903a8cb.png"
        },
        {
            "name": "Martinez",
            "country": "BEL",
            "country_attack": 3,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/3e/4f/39/2d/3e4f392d.png"
        },
        {
            "name": "Dalic",
            "country": "CRO",
            "country_attack": 3,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/67/ad/f4/96/67adf496.png"
        },
        {
            "name": "Southgate",
            "country": "ENG",
            "country_attack": 2,
            "country_defence": 3,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/e1/be/a4/60/e1bea460.png"
        },
        {
            "name": "Andersson",
            "country": "SWE",
            "country_attack": 2,
            "country_defence": 3,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/8f/5d/9e/37/8f5d9e37.png"
        },
        {
            "name": "Cherchesov",
            "country": "RUS",
            "country_attack": 3,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/8d/b6/56/b2/8db656b2.png"
        },
        {
            "name": "Tabarez",
            "country": "URU",
            "country_attack": 2,
            "country_defence": 3,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ce/7b/63/1f/ce7b631f.png"
        },
        {
            "name": "Tite",
            "country": "BRA",
            "country_attack": 1,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/04/56/26/ea/045626ea.png"
        },
        {
            "name": "Sampaoli",
            "country": "ARG",
            "country_attack": 1,
            "country_defence": 1,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f3/a3/63/b0/f3a363b0.png"
        },
        {
            "name": "F.Santos",
            "country": "POR",
            "country_attack": 2,
            "country_defence": 3,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/97/3a/4f/fa/973a4ffa.png"
        },
        {
            "name": "Osorio",
            "country": "MEX",
            "country_attack": 2,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/a9/d5/a8/40/a9d5a840.png"
        },
        {
            "name": "Nishino",
            "country": "JPA",
            "country_attack": 2,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/95/32/f8/c5/9532f8c5.png"
        },
        {
            "name": "Hareide",
            "country": "DEN",
            "country_attack": 1,
            "country_defence": 3,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/fa/24/f7/aa/fa24f7aa.png"
        },
        {
            "name": "Petkovic",
            "country": "SUI",
            "country_attack": 2,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/4c/8a/c8/16/4c8ac816.png"
        },
        {
            "name": "Pekerman",
            "country": "COL",
            "country_attack": 2,
            "country_defence": 2,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/f5/83/38/d8/f58338d8.png"
        },
        {
            "name": "Zidane",
            "country": "FRA",
            "country_attack": 1,
            "country_defence": 1,
            "club": "Real Madrid",
            "club_attack": 5,
            "club_defence": 5,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/96/59/6e/b4/96596eb4.png"
        },
        {
            "name": "Putin",
            "country": "RUS",
            "country_attack": 7,
            "country_defence": 7,
            "club": null,
            "club_attack": null,
            "club_defence": null,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/ee/6d/15/84/ee6d1584.png"
        },
        {
            "name": "Pochettino",
            "country": "ARG",
            "country_attack": 1,
            "country_defence": 1,
            "club": "Tottenham",
            "club_attack": 3,
            "club_defence": 2,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/45/84/fe/b8/4584feb8.png"
        },
        {
            "name": "Sir Alex Ferguson",
            "country": null,
            "country_attack": null,
            "country_defence": null,
            "club": "Man Utd",
            "club_attack": 6,
            "club_defence": 5,
            "url": "https://hearthcards.ams3.digitaloceanspaces.com/95/9f/e2/be/959fe2be.png"
        }
    ]
};