'use strict';

module.exports = {
    minions: [
        {
            "Name": "Pickford",
            "Country": "ENG",
            "Club": "Everton",
            "Position": "GK",
            "Cost": "10",
            "Attack": "5",
            "Defense": "16",
            "Special Trait": "Reflexes",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/22/4c/e2/0c/224ce20c.png"
        },
        {
            "Name": "Walker",
            "Country": "ENG",
            "Club": "Man City",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "8",
            "Defense": "14",
            "Special Trait": "Speed",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b2/c6/3a/4d/b2c63a4d.png"
        },
        {
            "Name": "Stones",
            "Country": "ENG",
            "Club": "Man City",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "6",
            "Defense": "14",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c1/29/55/94/c1295594.png"
        },
        {
            "Name": "Maguire",
            "Country": "ENG",
            "Club": "Leicester",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "9",
            "Defense": "12",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f1/5f/60/d5/f15f60d5.png"
        },
        {
            "Name": "Trippier",
            "Country": "ENG",
            "Club": "Tottenham",
            "Position": "MID",
            "Cost": "9",
            "Attack": "10",
            "Defense": "11",
            "Special Trait": "Free kick",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e0/06/10/8f/e006108f.png"
        },
        {
            "Name": "Henderson",
            "Country": "ENG",
            "Club": "Liverpool",
            "Position": "MID",
            "Cost": "8",
            "Attack": "8",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/70/af/3d/83/70af3d83.png"
        },
        {
            "Name": "Alli",
            "Country": "ENG",
            "Club": "Tottenham",
            "Position": "MID",
            "Cost": "10",
            "Attack": "12",
            "Defense": "11",
            "Special Trait": "Playmaker",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/5a/fa/3c/6b/5afa3c6b.png"
        },
        {
            "Name": "Lingard",
            "Country": "ENG",
            "Club": "Man Utd",
            "Position": "MID",
            "Cost": "8",
            "Attack": "11",
            "Defense": "9",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f6/50/90/00/f6509000.png"
        },
        {
            "Name": "Young",
            "Country": "ENG",
            "Club": "Man Utd",
            "Position": "MID",
            "Cost": "9",
            "Attack": "10",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/52/e1/5b/14/52e15b14.png"
        },
        {
            "Name": "Sterling",
            "Country": "ENG",
            "Club": "Man City",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "16",
            "Defense": "5",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/82/97/85/39/82978539.png"
        },
        {
            "Name": "Kane",
            "Country": "ENG",
            "Club": "Tottenham",
            "Position": "ATT",
            "Cost": "15",
            "Attack": "25",
            "Defense": "10",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/df/53/57/61/df535761.png"
        },
        {
            "Name": "Armani",
            "Country": "ARG",
            "Club": "River Plate",
            "Position": "GK",
            "Cost": "7",
            "Attack": "3",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e4/b5/a4/d7/e4b5a4d7.png"
        },
        {
            "Name": "Mercado",
            "Country": "ARG",
            "Club": "Sevilla",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "4",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b5/03/bc/a6/b503bca6.png"
        },
        {
            "Name": "Rojo",
            "Country": "ARG",
            "Club": "Man Utd",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "8",
            "Defense": "9",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a1/31/60/be/a13160be.png"
        },
        {
            "Name": "Otamendi",
            "Country": "ARG",
            "Club": "Man City",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0c/9f/66/35/0c9f6635.png"
        },
        {
            "Name": "Tagliafico",
            "Country": "ARG",
            "Club": "Ajax",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "7",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b6/9a/a3/65/b69aa365.png"
        },
        {
            "Name": "Mascherano",
            "Country": "ARG",
            "Club": "Hebei",
            "Position": "MID",
            "Cost": "7",
            "Attack": "4",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ae/28/74/17/ae287417.png"
        },
        {
            "Name": "Biglia",
            "Country": "ARG",
            "Club": "Milan",
            "Position": "MID",
            "Cost": "7",
            "Attack": "6",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/eb/ae/98/cc/ebae98cc.png"
        },
        {
            "Name": "Banega",
            "Country": "ARG",
            "Club": "Sevilla",
            "Position": "MID",
            "Cost": "7",
            "Attack": "7",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4f/c9/cc/c6/4fc9ccc6.png"
        },
        {
            "Name": "Di Maria",
            "Country": "ARG",
            "Club": "PSG",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "10",
            "Defense": "6",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/10/94/a3/8c/1094a38c.png"
        },
        {
            "Name": "Messi",
            "Country": "ARG",
            "Club": "Barcelona",
            "Position": "ATT",
            "Cost": "15",
            "Attack": "25",
            "Defense": "7",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/86/8f/60/2f/868f602f.png"
        },
        {
            "Name": "Aguero",
            "Country": "ARG",
            "Club": "Man City",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "16",
            "Defense": "5",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4c/ca/ac/4d/4ccaac4d.png"
        },
        {
            "Name": "Courtois",
            "Country": "BEL",
            "Club": "Real Madrid",
            "Position": "GK",
            "Cost": "12",
            "Attack": "6",
            "Defense": "18",
            "Special Trait": "Diving",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/35/fc/fc/23/35fcfc23.png"
        },
        {
            "Name": "Alderweireld",
            "Country": "BEL",
            "Club": "Tottenham",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "7",
            "Defense": "16",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/eb/10/09/28/eb100928.png"
        },
        {
            "Name": "Kompany",
            "Country": "BEL",
            "Club": "Man City",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "8",
            "Defense": "15",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0e/5b/98/0d/0e5b980d.png"
        },
        {
            "Name": "Vertonghen",
            "Country": "BEL",
            "Club": "Tottenham",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "8",
            "Defense": "16",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f1/46/92/2a/f146922a.png"
        },
        {
            "Name": "Meunier",
            "Country": "BEL",
            "Club": "PSG",
            "Position": "MID",
            "Cost": "10",
            "Attack": "10",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f9/ac/a5/a5/f9aca5a5.png"
        },
        {
            "Name": "Witsel",
            "Country": "BEL",
            "Club": "Dortmund",
            "Position": "MID",
            "Cost": "11",
            "Attack": "12",
            "Defense": "11",
            "Special Trait": "Ball control",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/18/cb/90/bf/18cb90bf.png"
        },
        {
            "Name": "Fellaini",
            "Country": "BEL",
            "Club": "Man Utd",
            "Position": "MID",
            "Cost": "10",
            "Attack": "9",
            "Defense": "12",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/74/9c/80/09/749c8009.png"
        },
        {
            "Name": "Chadli",
            "Country": "BEL",
            "Club": "Monaco",
            "Position": "MID",
            "Cost": "9",
            "Attack": "10",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/47/23/d3/76/4723d376.png"
        },
        {
            "Name": "De Bruyne",
            "Country": "BEL",
            "Club": "Man City",
            "Position": "ATT",
            "Cost": "12",
            "Attack": "15",
            "Defense": "11",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b6/31/48/c7/b63148c7.png"
        },
        {
            "Name": "Hazard",
            "Country": "BEL",
            "Club": "Chelsea",
            "Position": "ATT",
            "Cost": "13",
            "Attack": "19",
            "Defense": "10",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/32/96/e4/e8/3296e4e8.png"
        },
        {
            "Name": "Lukaku",
            "Country": "BEL",
            "Club": "Man Utd",
            "Position": "ATT",
            "Cost": "12",
            "Attack": "20",
            "Defense": "6",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/5c/30/eb/c0/5c30ebc0.png"
        },
        {
            "Name": "Alisson",
            "Country": "BRA",
            "Club": "Liverpool",
            "Position": "GK",
            "Cost": "11",
            "Attack": "6",
            "Defense": "17",
            "Special Trait": "Diving",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/8b/81/e1/11/8b81e111.png"
        },
        {
            "Name": "Fagner",
            "Country": "BRA",
            "Club": "Corinthians",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f0/22/63/81/f0226381.png"
        },
        {
            "Name": "Miranda",
            "Country": "BRA",
            "Club": "Inter",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "6",
            "Defense": "12",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ec/05/0a/15/ec050a15.png"
        },
        {
            "Name": "Thiago Silva",
            "Country": "BRA",
            "Club": "PSG",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "6",
            "Defense": "13",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/33/76/cd/67/3376cd67.png"
        },
        {
            "Name": "Marcelo",
            "Country": "BRA",
            "Club": "Real Madrid",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "10",
            "Defense": "11",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f5/f2/86/78/f5f28678.png"
        },
        {
            "Name": "Fernandinho",
            "Country": "BRA",
            "Club": "Man City",
            "Position": "MID",
            "Cost": "9",
            "Attack": "6",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/15/e6/c6/7f/15e6c67f.png"
        },
        {
            "Name": "Paulinho",
            "Country": "BRA",
            "Club": "Guangzhou",
            "Position": "MID",
            "Cost": "9",
            "Attack": "8",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/7c/b9/84/23/7cb98423.png"
        },
        {
            "Name": "Coutinho",
            "Country": "BRA",
            "Club": "Barcelona",
            "Position": "MID",
            "Cost": "11",
            "Attack": "15",
            "Defense": "8",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/82/cd/d3/de/82cdd3de.png"
        },
        {
            "Name": "Willian ",
            "Country": "BRA",
            "Club": "Chelsea",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "14",
            "Defense": "6",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4e/68/4e/82/4e684e82.png"
        },
        {
            "Name": "Neymar ",
            "Country": "BRA",
            "Club": "PSG",
            "Position": "ATT",
            "Cost": "12",
            "Attack": "18",
            "Defense": "6",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/5a/bc/0f/42/5abc0f42.png"
        },
        {
            "Name": "Gabriel Jesus",
            "Country": "BRA",
            "Club": "Man City",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "12",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/65/38/f9/ee/6538f9ee.png"
        },
        {
            "Name": "Ospina",
            "Country": "COL",
            "Club": "Napoli",
            "Position": "GK",
            "Cost": "8",
            "Attack": "6",
            "Defense": "12",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/dd/ac/a1/78/ddaca178.png"
        },
        {
            "Name": "Arias",
            "Country": "COL",
            "Club": "Atletico",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "8",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/45/12/21/1a/4512211a.png"
        },
        {
            "Name": "D.Sanchez",
            "Country": "COL",
            "Club": "Tottenham",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/cc/3c/02/72/cc3c0272.png"
        },
        {
            "Name": "Mina",
            "Country": "COL",
            "Club": "Everton",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "10",
            "Defense": "13",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/fc/de/62/ed/fcde62ed.png"
        },
        {
            "Name": "Mojica",
            "Country": "COL",
            "Club": "Girona",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "6",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c6/cd/a9/19/c6cda919.png"
        },
        {
            "Name": "C.Sanchez",
            "Country": "COL",
            "Club": "West Ham",
            "Position": "MID",
            "Cost": "8",
            "Attack": "6",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/bf/8c/7a/a8/bf8c7aa8.png"
        },
        {
            "Name": "Barrios",
            "Country": "COL",
            "Club": "Boca Juniors",
            "Position": "MID",
            "Cost": "8",
            "Attack": "5",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/80/e8/fd/74/80e8fd74.png"
        },
        {
            "Name": "Quintero",
            "Country": "COL",
            "Club": "River Plate",
            "Position": "MID",
            "Cost": "9",
            "Attack": "13",
            "Defense": "6",
            "Special Trait": "Playmaker",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/09/a2/0c/68/09a20c68.png"
        },
        {
            "Name": "Cuadrado",
            "Country": "COL",
            "Club": "Juventus",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "12",
            "Defense": "8",
            "Special Trait": "Speed",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e8/5c/1c/0a/e85c1c0a.png"
        },
        {
            "Name": "James",
            "Country": "COL",
            "Club": "Bayern",
            "Position": "ATT",
            "Cost": "11",
            "Attack": "15",
            "Defense": "8",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b0/76/99/2b/b076992b.png"
        },
        {
            "Name": "Falcao",
            "Country": "COL",
            "Club": "Monaco",
            "Position": "ATT",
            "Cost": "11",
            "Attack": "15",
            "Defense": "7",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/99/ac/10/15/99ac1015.png"
        },
        {
            "Name": "Subasic",
            "Country": "CRO",
            "Club": "Monaco",
            "Position": "GK",
            "Cost": "11",
            "Attack": "6",
            "Defense": "17",
            "Special Trait": "Reflexes",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e3/47/77/d7/e34777d7.png"
        },
        {
            "Name": "Vrsaljko",
            "Country": "CRO",
            "Club": "Inter",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "13",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/00/f4/95/0a/00f4950a.png"
        },
        {
            "Name": "Lovren",
            "Country": "CRO",
            "Club": "Liverpool",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "7",
            "Defense": "16",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/53/74/d7/d7/5374d7d7.png"
        },
        {
            "Name": "Vida",
            "Country": "CRO",
            "Club": "Besiktas",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "8",
            "Defense": "13",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/eb/b5/3f/8f/ebb53f8f.png"
        },
        {
            "Name": "Strinic",
            "Country": "CRO",
            "Club": "Milan",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/22/dc/69/24/22dc6924.png"
        },
        {
            "Name": "Brozovic",
            "Country": "CRO",
            "Club": "Inter",
            "Position": "MID",
            "Cost": "9",
            "Attack": "9",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0b/09/94/6d/0b09946d.png"
        },
        {
            "Name": "Rakitic",
            "Country": "CRO",
            "Club": "Barcelona",
            "Position": "MID",
            "Cost": "11",
            "Attack": "12",
            "Defense": "11",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a4/e2/f5/1e/a4e2f51e.png"
        },
        {
            "Name": "Modric",
            "Country": "CRO",
            "Club": "Real Madrid",
            "Position": "MID",
            "Cost": "14",
            "Attack": "16",
            "Defense": "16",
            "Special Trait": "Playmaker",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f4/82/1b/c6/f4821bc6.png"
        },
        {
            "Name": "Rebic",
            "Country": "CRO",
            "Club": "Frankfurt",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "15",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/79/55/9c/54/79559c54.png"
        },
        {
            "Name": "Perisic",
            "Country": "CRO",
            "Club": "Inter ",
            "Position": "ATT",
            "Cost": "12",
            "Attack": "17",
            "Defense": "8",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ef/4d/4f/63/ef4d4f63.png"
        },
        {
            "Name": "Mandzukic",
            "Country": "CRO",
            "Club": "Juventus",
            "Position": "ATT",
            "Cost": "12",
            "Attack": "18",
            "Defense": "8",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/fc/83/27/5b/fc83275b.png"
        },
        {
            "Name": "Schmeichel",
            "Country": "DEN",
            "Club": "Leicester",
            "Position": "GK",
            "Cost": "11",
            "Attack": "6",
            "Defense": "17",
            "Special Trait": "Diving",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c5/6a/bd/c8/c56abdc8.png"
        },
        {
            "Name": "Dalsgaard",
            "Country": "DEN",
            "Club": "Brentford",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/00/24/9b/5e/00249b5e.png"
        },
        {
            "Name": "Zanka",
            "Country": "DEN",
            "Club": "Huddersfield",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/7b/e0/a9/73/7be0a973.png"
        },
        {
            "Name": "Kjaer",
            "Country": "DEN",
            "Club": "Sevilla",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "7",
            "Defense": "11",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0e/dc/67/d1/0edc67d1.png"
        },
        {
            "Name": "Larsen",
            "Country": "DEN",
            "Club": "Udinese",
            "Position": "DEF",
            "Cost": "6",
            "Attack": "5",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0f/bb/d7/98/0fbbd798.png"
        },
        {
            "Name": "Christensen",
            "Country": "DEN",
            "Club": "Chelsea",
            "Position": "MID",
            "Cost": "9",
            "Attack": "6",
            "Defense": "12",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ce/ed/ee/d6/ceedeed6.png"
        },
        {
            "Name": "Delaney",
            "Country": "DEN",
            "Club": "Dortmund",
            "Position": "MID",
            "Cost": "9",
            "Attack": "9",
            "Defense": "10",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/32/1d/9f/aa/321d9faa.png"
        },
        {
            "Name": "Eriksen",
            "Country": "DEN",
            "Club": "Tottenham",
            "Position": "MID",
            "Cost": "11",
            "Attack": "15",
            "Defense": "9",
            "Special Trait": "Ball control",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/81/bf/59/0d/81bf590d.png"
        },
        {
            "Name": "Braithwaite",
            "Country": "DEN",
            "Club": "Middlesbrough",
            "Position": "ATT",
            "Cost": "7",
            "Attack": "9",
            "Defense": "4",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f9/5e/fa/20/f95efa20.png"
        },
        {
            "Name": "Sisto",
            "Country": "DEN",
            "Club": "Celta Vigo",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "12",
            "Defense": "5",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/78/12/3b/8c/78123b8c.png"
        },
        {
            "Name": "Poulsen",
            "Country": "DEN",
            "Club": "Leipzig",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "13",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/7d/fc/1f/6a/7dfc1f6a.png"
        },
        {
            "Name": "Sommer",
            "Country": "SUI",
            "Club": "Gladbach",
            "Position": "GK",
            "Cost": "9",
            "Attack": "5",
            "Defense": "13",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/78/40/6c/a0/78406ca0.png"
        },
        {
            "Name": "Lang",
            "Country": "SUI",
            "Club": "Gladbach",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b9/13/b7/42/b913b742.png"
        },
        {
            "Name": "Akanji",
            "Country": "SUI",
            "Club": "Dortmund",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "8",
            "Defense": "13",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e8/43/77/82/e8437782.png"
        },
        {
            "Name": "Droujou",
            "Country": "SUI",
            "Club": "SPAL",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "6",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/30/27/fc/54/3027fc54.png"
        },
        {
            "Name": "Rodriguez",
            "Country": "SUI",
            "Club": "Milan",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "7",
            "Defense": "11",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/25/ed/9f/a3/25ed9fa3.png"
        },
        {
            "Name": "Xhaka",
            "Country": "SUI",
            "Club": "Arsenal",
            "Position": "MID",
            "Cost": "10",
            "Attack": "12",
            "Defense": "8",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/eb/36/14/68/eb361468.png"
        },
        {
            "Name": "Behrami",
            "Country": "SUI",
            "Club": "Udinese",
            "Position": "MID",
            "Cost": "7",
            "Attack": "7",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f5/75/d5/3e/f575d53e.png"
        },
        {
            "Name": "Dzemaili",
            "Country": "SUI",
            "Club": "Bologna",
            "Position": "MID",
            "Cost": "7",
            "Attack": "7",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/9b/91/fd/2c/9b91fd2c.png"
        },
        {
            "Name": "Shaqiri",
            "Country": "SUI",
            "Club": "Liverpool",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "14",
            "Defense": "7",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f8/1f/34/d5/f81f34d5.png"
        },
        {
            "Name": "Zuber",
            "Country": "SUI",
            "Club": "Hoffenheim",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "12",
            "Defense": "7",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/76/8b/2e/fa/768b2efa.png"
        },
        {
            "Name": "Seferovic",
            "Country": "SUI",
            "Club": "Benfica",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "11",
            "Defense": "5",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/2d/a7/46/65/2da74665.png"
        },
        {
            "Name": "Lloris",
            "Country": "FRA",
            "Club": "Tottenham",
            "Position": "GK",
            "Cost": "11",
            "Attack": "6",
            "Defense": "17",
            "Special Trait": "Diving",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/29/19/07/54/29190754.png"
        },
        {
            "Name": "Pavard",
            "Country": "FRA",
            "Club": "Stuttgart",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "9",
            "Defense": "15",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/06/59/3a/4a/06593a4a.png"
        },
        {
            "Name": "Umtiti",
            "Country": "FRA",
            "Club": "Barcelona",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "8",
            "Defense": "13",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/5c/d0/d0/67/5cd0d067.png"
        },
        {
            "Name": "Varane",
            "Country": "FRA",
            "Club": "Real Madrid",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "14",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f2/ac/b7/90/f2acb790.png"
        },
        {
            "Name": "Hernandez",
            "Country": "FRA",
            "Club": "Atletico",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "14",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/8e/f3/fc/38/8ef3fc38.png"
        },
        {
            "Name": "Kante",
            "Country": "FRA",
            "Club": "Chelsea",
            "Position": "MID",
            "Cost": "11",
            "Attack": "8",
            "Defense": "16",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/71/95/bf/bc/7195bfbc.png"
        },
        {
            "Name": "Pogba",
            "Country": "FRA",
            "Club": "Man Utd",
            "Position": "MID",
            "Cost": "11",
            "Attack": "12",
            "Defense": "11",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a6/67/4b/05/a6674b05.png"
        },
        {
            "Name": "Matuidi",
            "Country": "FRA",
            "Club": "Juventus",
            "Position": "MID",
            "Cost": "10",
            "Attack": "8",
            "Defense": "12",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ae/a7/9b/2e/aea79b2e.png"
        },
        {
            "Name": "Mbappe",
            "Country": "FRA",
            "Club": "PSG",
            "Position": "ATT",
            "Cost": "13",
            "Attack": "21",
            "Defense": "9",
            "Special Trait": "Speed",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/d4/b3/4f/d1/d4b34fd1.png"
        },
        {
            "Name": "Griezmann",
            "Country": "FRA",
            "Club": "Atletico",
            "Position": "ATT",
            "Cost": "13",
            "Attack": "19",
            "Defense": "10",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/25/e0/35/5a/25e0355a.png"
        },
        {
            "Name": "Giroud",
            "Country": "FRA",
            "Club": "Chelsea",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "12",
            "Defense": "6",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/97/2c/9b/e4/972c9be4.png"
        },
        {
            "Name": "Kawashima",
            "Country": "JPA",
            "Club": "Strasbourg",
            "Position": "GK",
            "Cost": "7",
            "Attack": "5",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/1b/34/8e/fb/1b348efb.png"
        },
        {
            "Name": "Sakai",
            "Country": "JPA",
            "Club": "Marseille",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "6",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/dc/47/82/5c/dc47825c.png"
        },
        {
            "Name": "Shoji",
            "Country": "JPA",
            "Club": "Kashima",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "4",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/3f/54/bc/07/3f54bc07.png"
        },
        {
            "Name": "Yoshida",
            "Country": "JPA",
            "Club": "Southampton",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f6/f1/47/03/f6f14703.png"
        },
        {
            "Name": "Nagatomo",
            "Country": "JPA",
            "Club": "Galatasaray",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "6",
            "Defense": "8",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/91/0a/16/89/910a1689.png"
        },
        {
            "Name": "Hasebe",
            "Country": "JPA",
            "Club": "Frankfurt",
            "Position": "MID",
            "Cost": "7",
            "Attack": "6",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/cf/8a/8a/b0/cf8a8ab0.png"
        },
        {
            "Name": "Shibasaki",
            "Country": "JPA",
            "Club": "Getafe",
            "Position": "MID",
            "Cost": "7",
            "Attack": "6",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f3/e2/14/05/f3e21405.png"
        },
        {
            "Name": "Kagawa",
            "Country": "JPA",
            "Club": "Dortmund",
            "Position": "MID",
            "Cost": "8",
            "Attack": "10",
            "Defense": "7",
            "Special Trait": "Playmaker",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/3e/26/26/da/3e2626da.png"
        },
        {
            "Name": "Haraguchi",
            "Country": "JPA",
            "Club": "Hannover",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "10",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/36/cc/63/34/36cc6334.png"
        },
        {
            "Name": "Inui",
            "Country": "JPA",
            "Club": "Betis",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "11",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/85/23/86/97/85238697.png"
        },
        {
            "Name": "Osako",
            "Country": "JPA",
            "Club": "Bremen",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "12",
            "Defense": "5",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/9a/48/6a/6d/9a486a6d.png"
        },
        {
            "Name": "Ochoa",
            "Country": "MEX",
            "Club": "Standard",
            "Position": "GK",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "Diving",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a2/c5/bc/68/a2c5bc68.png"
        },
        {
            "Name": "Layun",
            "Country": "MEX",
            "Club": "Villarreal",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/34/f4/0b/81/34f40b81.png"
        },
        {
            "Name": "Salcedo",
            "Country": "MEX",
            "Club": "Frankfurt",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/10/83/f6/26/1083f626.png"
        },
        {
            "Name": "Ayala",
            "Country": "MEX",
            "Club": "UNAL",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/cf/e2/98/09/cfe29809.png"
        },
        {
            "Name": "Gallardo",
            "Country": "MEX",
            "Club": "Monterrey",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "6",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/8f/57/56/9e/8f57569e.png"
        },
        {
            "Name": "Marquez",
            "Country": "MEX",
            "Club": "Atlas",
            "Position": "MID",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/d5/76/de/47/d576de47.png"
        },
        {
            "Name": "Guardado",
            "Country": "MEX",
            "Club": "Betis",
            "Position": "MID",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f8/22/af/41/f822af41.png"
        },
        {
            "Name": "Herrera",
            "Country": "MEX",
            "Club": "Porto",
            "Position": "MID",
            "Cost": "8",
            "Attack": "8",
            "Defense": "9",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/58/45/6e/ec/58456eec.png"
        },
        {
            "Name": "Vela",
            "Country": "MEX",
            "Club": "Los Angeles",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "12",
            "Defense": "5",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/fa/b0/d0/cc/fab0d0cc.png"
        },
        {
            "Name": "Lozano",
            "Country": "MEX",
            "Club": "PSV",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "14",
            "Defense": "5",
            "Special Trait": "Speed",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/42/28/18/be/422818be.png"
        },
        {
            "Name": "Chicharito",
            "Country": "MEX",
            "Club": "West Ham",
            "Position": "ATT",
            "Cost": "8",
            "Attack": "10",
            "Defense": "5",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/fc/7e/42/8f/fc7e428f.png"
        },
        {
            "Name": "Rui Patricio",
            "Country": "POR",
            "Club": "Wolves",
            "Position": "GK",
            "Cost": "8",
            "Attack": "5",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/16/78/ec/0d/1678ec0d.png"
        },
        {
            "Name": "Cedric",
            "Country": "POR",
            "Club": "Southampton",
            "Position": "DEF",
            "Cost": "7",
            "Attack": "5",
            "Defense": "9",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/62/9f/14/04/629f1404.png"
        },
        {
            "Name": "Pepe",
            "Country": "POR",
            "Club": "Besiktas",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "14",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/1c/3e/74/25/1c3e7425.png"
        },
        {
            "Name": "Fonte",
            "Country": "POR",
            "Club": "Lille",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "5",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c2/43/15/8e/c243158e.png"
        },
        {
            "Name": "Guerreiro",
            "Country": "POR",
            "Club": "Dortmund",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "7",
            "Defense": "10",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/dd/f0/a2/2a/ddf0a22a.png"
        },
        {
            "Name": "W.Carvalho",
            "Country": "POR",
            "Club": "Betis",
            "Position": "MID",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/85/75/8c/0d/85758c0d.png"
        },
        {
            "Name": "Moutinho",
            "Country": "POR",
            "Club": "Wolves",
            "Position": "MID",
            "Cost": "7",
            "Attack": "6",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/83/ea/23/3a/83ea233a.png"
        },
        {
            "Name": "B.Silva",
            "Country": "POR",
            "Club": "Man City",
            "Position": "MID",
            "Cost": "9",
            "Attack": "12",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/86/d2/eb/40/86d2eb40.png"
        },
        {
            "Name": "Guedes",
            "Country": "POR",
            "Club": "Valencia",
            "Position": "MID",
            "Cost": "8",
            "Attack": "9",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/bf/43/e4/73/bf43e473.png"
        },
        {
            "Name": "C.Ronaldo",
            "Country": "POR",
            "Club": "Juventus",
            "Position": "ATT",
            "Cost": "15",
            "Attack": "25",
            "Defense": "8",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b1/36/ce/cf/b136cecf.png"
        },
        {
            "Name": "A.Silva",
            "Country": "POR",
            "Club": "Sevilla",
            "Position": "ATT",
            "Cost": "7",
            "Attack": "10",
            "Defense": "3",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/bc/83/69/76/bc836976.png"
        },
        {
            "Name": "Akinfeev",
            "Country": "RUS",
            "Club": "CSKA",
            "Position": "GK",
            "Cost": "10",
            "Attack": "6",
            "Defense": "16",
            "Special Trait": "Reflexes",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/09/7d/2f/dd/097d2fdd.png"
        },
        {
            "Name": "M.Fernandes",
            "Country": "RUS",
            "Club": "CSKA",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "14",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4e/dd/5c/01/4edd5c01.png"
        },
        {
            "Name": "Ignashevich",
            "Country": "RUS",
            "Club": "CSKA",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "6",
            "Defense": "13",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/41/68/2d/63/41682d63.png"
        },
        {
            "Name": "Kutepov",
            "Country": "RUS",
            "Club": "Spartak",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4f/ef/9d/e7/4fef9de7.png"
        },
        {
            "Name": "Zhirkov",
            "Country": "RUS",
            "Club": "Zenit",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/73/a8/be/6e/73a8be6e.png"
        },
        {
            "Name": "Gazinsky",
            "Country": "RUS",
            "Club": "Krasnodar",
            "Position": "MID",
            "Cost": "9",
            "Attack": "8",
            "Defense": "11",
            "Special Trait": "Ball control",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4a/f2/2b/c4/4af22bc4.png"
        },
        {
            "Name": "Zobnin",
            "Country": "RUS",
            "Club": "Spartak",
            "Position": "MID",
            "Cost": "9",
            "Attack": "7",
            "Defense": "12",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/3f/b8/91/44/3fb89144.png"
        },
        {
            "Name": "Golovin",
            "Country": "RUS",
            "Club": "Monaco",
            "Position": "MID",
            "Cost": "11",
            "Attack": "15",
            "Defense": "10",
            "Special Trait": "Playmaker",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c1/87/34/9a/c187349a.png"
        },
        {
            "Name": "Samedov",
            "Country": "RUS",
            "Club": "Spartak",
            "Position": "ATT",
            "Cost": "7",
            "Attack": "8",
            "Defense": "5",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/23/0c/11/f7/230c11f7.png"
        },
        {
            "Name": "Cheryshev",
            "Country": "RUS",
            "Club": "Valencia",
            "Position": "ATT",
            "Cost": "11",
            "Attack": "16",
            "Defense": "9",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f7/e9/49/24/f7e94924.png"
        },
        {
            "Name": "Dzyuba",
            "Country": "RUS",
            "Club": "Zenit",
            "Position": "ATT",
            "Cost": "11",
            "Attack": "17",
            "Defense": "8",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ba/17/cb/6f/ba17cb6f.png"
        },
        {
            "Name": "De Gea",
            "Country": "ESP",
            "Club": "Man Utd",
            "Position": "GK",
            "Cost": "10",
            "Attack": "6",
            "Defense": "13",
            "Special Trait": "Reflexes",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b6/2b/ee/11/b62bee11.png"
        },
        {
            "Name": "Carvajal",
            "Country": "ESP",
            "Club": "Real Madrid",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "6",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/8f/62/bc/54/8f62bc54.png"
        },
        {
            "Name": "Ramos",
            "Country": "ESP",
            "Club": "Real Madrid",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "7",
            "Defense": "13",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a1/bb/97/12/a1bb9712.png"
        },
        {
            "Name": "Pique",
            "Country": "ESP",
            "Club": "Barcelona",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "6",
            "Defense": "13",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/86/dc/f5/41/86dcf541.png"
        },
        {
            "Name": "J.Alba",
            "Country": "ESP",
            "Club": "Barcelona",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "7",
            "Defense": "11",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/10/ee/2d/3a/10ee2d3a.png"
        },
        {
            "Name": "Busquets",
            "Country": "ESP",
            "Club": "Barcelona",
            "Position": "MID",
            "Cost": "9",
            "Attack": "5",
            "Defense": "13",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4b/12/ae/ec/4b12aeec.png"
        },
        {
            "Name": "Koke",
            "Country": "ESP",
            "Club": "Atletico",
            "Position": "MID",
            "Cost": "8",
            "Attack": "7",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ea/4c/0f/27/ea4c0f27.png"
        },
        {
            "Name": "D.Silva",
            "Country": "ESP",
            "Club": "Man City",
            "Position": "MID",
            "Cost": "10",
            "Attack": "12",
            "Defense": "8",
            "Special Trait": "Passing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c0/c3/e1/e3/c0c3e1e3.png"
        },
        {
            "Name": "Isco",
            "Country": "ESP",
            "Club": "Real Madrid",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "13",
            "Defense": "8",
            "Special Trait": "Dribbling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/83/d1/58/a6/83d158a6.png"
        },
        {
            "Name": "Asensio",
            "Country": "ESP",
            "Club": "Real Madrid",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "11",
            "Defense": "7",
            "Special Trait": "Long shot",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/96/83/65/24/96836524.png"
        },
        {
            "Name": "D.Costa",
            "Country": "ESP",
            "Club": "Atletico",
            "Position": "ATT",
            "Cost": "9",
            "Attack": "13",
            "Defense": "6",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/d8/5b/2c/23/d85b2c23.png"
        },
        {
            "Name": "Olsen",
            "Country": "SWE",
            "Club": "Roma",
            "Position": "GK",
            "Cost": "11",
            "Attack": "8",
            "Defense": "16",
            "Special Trait": "Reflexes",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/24/2d/e7/a2/242de7a2.png"
        },
        {
            "Name": "Lustig",
            "Country": "SWE",
            "Club": "Celtic",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "13",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0d/ca/d3/01/0dcad301.png"
        },
        {
            "Name": "Granqvist",
            "Country": "SWE",
            "Club": "Helsingborgs",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "8",
            "Defense": "16",
            "Special Trait": "Strength",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/38/c9/29/3b/38c9293b.png"
        },
        {
            "Name": "Lindelhof",
            "Country": "SWE",
            "Club": "Man Utd",
            "Position": "DEF",
            "Cost": "9",
            "Attack": "6",
            "Defense": "12",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c2/0e/8f/95/c20e8f95.png"
        },
        {
            "Name": "Augustinsson",
            "Country": "SWE",
            "Club": "Bremen",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "5",
            "Defense": "11",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/bb/42/1c/ba/bb421cba.png"
        },
        {
            "Name": "Claesson",
            "Country": "SWE",
            "Club": "Krasnodar",
            "Position": "MID",
            "Cost": "8",
            "Attack": "11",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/dc/a5/3f/8b/dca53f8b.png"
        },
        {
            "Name": "Ekdal",
            "Country": "SWE",
            "Club": "Sampdoria",
            "Position": "MID",
            "Cost": "8",
            "Attack": "8",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/82/43/1a/3e/82431a3e.png"
        },
        {
            "Name": "Larsson",
            "Country": "SWE",
            "Club": "AIK",
            "Position": "MID",
            "Cost": "8",
            "Attack": "9",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/6a/9f/81/e5/6a9f81e5.png"
        },
        {
            "Name": "Forsberg",
            "Country": "SWE",
            "Club": "Leipzig",
            "Position": "MID",
            "Cost": "10",
            "Attack": "13",
            "Defense": "8",
            "Special Trait": "Crossing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/7f/6a/07/08/7f6a0708.png"
        },
        {
            "Name": "Berg",
            "Country": "SWE",
            "Club": "Al Ain",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "15",
            "Defense": "7",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ea/d3/58/b3/ead358b3.png"
        },
        {
            "Name": "Toivonen",
            "Country": "SWE",
            "Club": "Melbourne",
            "Position": "ATT",
            "Cost": "10",
            "Attack": "14",
            "Defense": "7",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/86/8a/1c/e3/868a1ce3.png"
        },
        {
            "Name": "Muslera",
            "Country": "URU",
            "Club": "Galatasaray",
            "Position": "GK",
            "Cost": "8",
            "Attack": "5",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e8/6a/ad/29/e86aad29.png"
        },
        {
            "Name": "Caceres",
            "Country": "URU",
            "Club": "Lazio",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/29/a9/04/24/29a90424.png"
        },
        {
            "Name": "Godin",
            "Country": "URU",
            "Club": "Atletico",
            "Position": "DEF",
            "Cost": "11",
            "Attack": "7",
            "Defense": "16",
            "Special Trait": "Heading",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/97/93/f0/a5/9793f0a5.png"
        },
        {
            "Name": "Gimenez",
            "Country": "URU",
            "Club": "Atletico",
            "Position": "DEF",
            "Cost": "10",
            "Attack": "6",
            "Defense": "14",
            "Special Trait": "Tackling",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/24/f3/3a/57/24f33a57.png"
        },
        {
            "Name": "Laxalt",
            "Country": "URU",
            "Club": "Milan",
            "Position": "DEF",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/52/e1/f4/ef/52e1f4ef.png"
        },
        {
            "Name": "Torreira",
            "Country": "URU",
            "Club": "Arsenal",
            "Position": "MID",
            "Cost": "8",
            "Attack": "8",
            "Defense": "8",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/2b/10/2e/a9/2b102ea9.png"
        },
        {
            "Name": "Vecino",
            "Country": "URU",
            "Club": "Inter",
            "Position": "MID",
            "Cost": "8",
            "Attack": "6",
            "Defense": "10",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/b5/6b/4d/43/b56b4d43.png"
        },
        {
            "Name": "Nandez",
            "Country": "URU",
            "Club": "Boca Juniors",
            "Position": "MID",
            "Cost": "7",
            "Attack": "6",
            "Defense": "7",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0b/0a/1f/c7/0b0a1fc7.png"
        },
        {
            "Name": "Bentancur",
            "Country": "URU",
            "Club": "Juventus",
            "Position": "MID",
            "Cost": "7",
            "Attack": "8",
            "Defense": "6",
            "Special Trait": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/1d/20/21/2e/1d20212e.png"
        },
        {
            "Name": "Suarez",
            "Country": "URU",
            "Club": "Barcelona",
            "Position": "ATT",
            "Cost": "11",
            "Attack": "17",
            "Defense": "8",
            "Special Trait": "Free kick",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c4/e4/ba/fd/c4e4bafd.png"
        },
        {
            "Name": "Cavani",
            "Country": "URU",
            "Club": "PSG",
            "Position": "ATT",
            "Cost": "11",
            "Attack": "17",
            "Defense": "8",
            "Special Trait": "Finishing",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/21/3b/da/2b/213bda2b.png"
        }
    ],
    functional: [
        [
            {
                "Name ": "Yellow Card",
                "Who applies to": "Opposition",
                "Attack": "null",
                "For total attack": "no",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "-5",
                "For total defence": "yes",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/bc/5d/18/47/bc5d1847.png",
                "": ""
            },
            {
                "Name ": "Red Card",
                "Who applies to": "Opposition",
                "Attack": "-10",
                "For total attack": "yes",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "-10",
                "For total defence": "yes",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/79/51/3d/6a/79513d6a.png",
                "": ""
            },
            {
                "Name ": "Corner",
                "Who applies to": "My team",
                "Attack": "5",
                "For total attack": "no",
                "Attack special trait 1": "Crossing",
                "Attack special trait 2": "Heading",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/1f/ab/8e/b3/1fab8eb3.png",
                "": ""
            },
            {
                "Name ": "Penalty",
                "Who applies to": "My team",
                "Attack": "10",
                "For total attack": "no",
                "Attack special trait 1": "Finishing",
                "Attack special trait 2": "null",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e2/95/09/e0/e29509e0.png",
                "": ""
            },
            {
                "Name ": "Free Kick",
                "Who applies to": "My team",
                "Attack": "7",
                "For total attack": "no",
                "Attack special trait 1": "Long shot",
                "Attack special trait 2": "Free kick",
                "Defence": "null",
                "For total defence": "no ",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/34/f9/3a/c3/34f93ac3.png",
                "": ""
            },
            {
                "Name ": "Counter Attack",
                "Who applies to": "My team",
                "Attack": "7",
                "For total attack": "no ",
                "Attack special trait 1": "Dribbling",
                "Attack special trait 2": "Speed",
                "Defence": "null",
                "For total defence": "no ",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/82/67/55/15/82675515.png",
                "": ""
            },
            {
                "Name ": "Tap In",
                "Who applies to": "My team",
                "Attack": "5",
                "For total attack": "no",
                "Attack special trait 1": "Crossing",
                "Attack special trait 2": "Finishing",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/17/49/1e/b8/17491eb8.png",
                "": ""
            },
            {
                "Name ": "Target Man",
                "Who applies to": "My team",
                "Attack": "5",
                "For total attack": "no",
                "Attack special trait 1": "Heading",
                "Attack special trait 2": "Ball controll",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/0d/cf/b8/69/0dcfb869.png",
                "": ""
            },
            {
                "Name ": "Park the Bus",
                "Who applies to": "My team",
                "Attack": "null",
                "For total attack": "no",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "10",
                "For total defence": "yes",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/59/ce/90/07/59ce9007.png",
                "": ""
            },
            {
                "Name ": "Ultra Attack",
                "Who applies to": "My team",
                "Attack": "10",
                "For total attack": "yes",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e6/e6/a2/74/e6e6a274.png",
                "": ""
            },
            {
                "Name ": "Heavy Rain",
                "Who applies to": "All",
                "Attack": "3",
                "For total attack": "no",
                "Attack special trait 1": "Tackling",
                "Attack special trait 2": "Long shot",
                "Defence": "-5",
                "For total defence": "no",
                "Defence special trait 1": "Dribbling",
                "Defence special trait 2": "Ball control",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/5f/7a/b3/73/5f7ab373.png",
                "": ""
            },
            {
                "Name ": "Disaster",
                "Who applies to": "All",
                "Attack": "-all",
                "For total attack": "yes",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "-all",
                "For total defence": "yes",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f6/8a/5c/bd/f68a5cbd.png",
                "": ""
            },
            {
                "Name ": "Melee",
                "Who applies to": "All",
                "Attack": "-10",
                "For total attack": "yes",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "-10",
                "For total defence": "yes",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f7/c6/f1/6f/f7c6f16f.png",
                "": ""
            },
            {
                "Name ": "Tiki Taka",
                "Who applies to": "My team",
                "Attack": "8",
                "For total attack": "no",
                "Attack special trait 1": "Passing",
                "Attack special trait 2": "Ball controll",
                "Defence": "null",
                "For total defence": "no ",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ac/4e/52/1f/ac4e521f.png",
                "": ""
            },
            {
                "Name ": "Physical Game",
                "Who applies to": "All",
                "Attack": "-3",
                "For total attack": "no",
                "Attack special trait 1": "Dribbling",
                "Attack special trait 2": "Ball controll",
                "Defence": "7",
                "For total defence": "no",
                "Defence special trait 1": "Strength",
                "Defence special trait 2": "Tackling",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/6b/c3/eb/0e/6bc3eb0e.png",
                "": ""
            },
            {
                "Name ": "Show",
                "Who applies to": "All",
                "Attack": "2",
                "For total attack": "no",
                "Attack special trait 1": "not null",
                "Attack special trait 2": "null",
                "Defence": "2",
                "For total defence": "no",
                "Defence special trait 1": "not null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/31/67/42/9e/3167429e.png"
            },
            {
                "Name ": "Joga Bonito",
                "Who applies to": "All",
                "Attack": "10",
                "For total attack": "no",
                "Attack special trait 1": "Dribbling",
                "Attack special trait 2": "null",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/aa/ab/29/e4/aaab29e4.png"
            },
            {
                "Name ": "Fog",
                "Who applies to": "All",
                "Attack": "10",
                "For total attack": "no",
                "Attack special trait 1": "Playmaker",
                "Attack special trait 2": "null",
                "Defence": "null",
                "For total defence": "no",
                "Defence special trait 1": "null",
                "Defence special trait 2": "null",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/c6/09/e4/e5/c609e4e5.png"
            },
            {
                "Name ": "Flying High",
                "Who applies to": "My team",
                "Attack": "null",
                "For total attack": "no",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "8",
                "For total defence": "no",
                "Defence special trait 1": "Diving",
                "Defence special trait 2": "Reflexes",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/99/ab/b3/34/99abb334.png"
            },
            {
                "Name ": "Slippery",
                "Who applies to": "Opposition",
                "Attack": "null",
                "For total attack": "no",
                "Attack special trait 1": "null",
                "Attack special trait 2": "null",
                "Defence": "-5",
                "For total defence": "no",
                "Defence special trait 1": "Diving",
                "Defence special trait 2": "Reflexes",
                "URL": "https://hearthcards.ams3.digitaloceanspaces.com/9b/12/0c/a9/9b120ca9.png"
            }
        ]
    ],
    heroes: [
        {
            "Name ": "Deschamps",
            "Country": "FRA",
            "Country Attack": "3",
            "Country Defence": "3",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a0/0c/3f/e0/a00c3fe0.png"
        },
        {
            "Name ": "Lopetegui",
            "Country": "ESP",
            "Country Attack": "-2",
            "Country Defence": "-2",
            "Club": "Real Madrid",
            "Club Attack": "2",
            "Club Defence": "2",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a9/03/a8/cb/a903a8cb.png"
        },
        {
            "Name ": "Martinez",
            "Country": "BEL",
            "Country Attack": "3",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/3e/4f/39/2d/3e4f392d.png"
        },
        {
            "Name ": "Dalic",
            "Country": "CRO",
            "Country Attack": "3",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/67/ad/f4/96/67adf496.png"
        },
        {
            "Name ": "Southgate",
            "Country": "ENG",
            "Country Attack": "2",
            "Country Defence": "3",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/e1/be/a4/60/e1bea460.png"
        },
        {
            "Name ": "Andersson",
            "Country": "SWE",
            "Country Attack": "2",
            "Country Defence": "3",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/8f/5d/9e/37/8f5d9e37.png"
        },
        {
            "Name ": "Cherchesov",
            "Country": "RUS",
            "Country Attack": "3",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/8d/b6/56/b2/8db656b2.png"
        },
        {
            "Name ": "Tabarez",
            "Country": "URU",
            "Country Attack": "2",
            "Country Defence": "3",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ce/7b/63/1f/ce7b631f.png"
        },
        {
            "Name ": "Tite",
            "Country": "BRA",
            "Country Attack": "1",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/04/56/26/ea/045626ea.png"
        },
        {
            "Name ": "Sampaoli",
            "Country": "ARG",
            "Country Attack": "1",
            "Country Defence": "1",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f3/a3/63/b0/f3a363b0.png"
        },
        {
            "Name ": "F.Santos",
            "Country": "POR",
            "Country Attack": "2",
            "Country Defence": "3",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/97/3a/4f/fa/973a4ffa.png"
        },
        {
            "Name ": "Osorio",
            "Country": "MEX",
            "Country Attack": "2",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/a9/d5/a8/40/a9d5a840.png"
        },
        {
            "Name ": "Nishino",
            "Country": "JPA",
            "Country Attack": "2",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/95/32/f8/c5/9532f8c5.png"
        },
        {
            "Name ": "Hareide ",
            "Country": "DEN",
            "Country Attack": "1",
            "Country Defence": "3",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/fa/24/f7/aa/fa24f7aa.png"
        },
        {
            "Name ": "Petkovic",
            "Country": "SUI",
            "Country Attack": "2",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/4c/8a/c8/16/4c8ac816.png"
        },
        {
            "Name ": "Pekerman",
            "Country": "COL",
            "Country Attack": "2",
            "Country Defence": "2",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/f5/83/38/d8/f58338d8.png"
        },
        {
            "Name ": "Zidane",
            "Country": "FRA",
            "Country Attack": "1",
            "Country Defence": "1",
            "Club": "Real Madrid",
            "Club Attack": "5",
            "Club Defence": "5",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/96/59/6e/b4/96596eb4.png"
        },
        {
            "Name ": "Putin",
            "Country": "RUS",
            "Country Attack": "7",
            "Country Defence": "7",
            "Club": "null",
            "Club Attack": "null",
            "Club Defence": "null",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/ee/6d/15/84/ee6d1584.png"
        },
        {
            "Name ": "Pochettino",
            "Country": "ARG",
            "Country Attack": "1",
            "Country Defence": "1",
            "Club": "Tottenham",
            "Club Attack": "3",
            "Club Defence": "2",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/45/84/fe/b8/4584feb8.png"
        },
        {
            "Name ": "Sir Alex Ferguson",
            "Country": "null",
            "Country Attack": "null",
            "Country Defence": "null",
            "Club": "Man Utd",
            "Club Attack": "6",
            "Club Defence": "5",
            "URL": "https://hearthcards.ams3.digitaloceanspaces.com/95/9f/e2/be/959fe2be.png"
        }
    ]
};